# Generated by Django 3.0.6 on 2020-05-30 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='main.Category', verbose_name='Категория'),
        ),
    ]
